---
title: "Udacity - EDA using R"
output:
  html_document:
    fig_height: 7
    fig.width: 9
    dpi: 144
    theme: cerulean
    toc: yes
---

Exercises from Udacity's Exploratory Data Analysis in R MOOC


```{r, echo=FALSE, message=FALSE, eval=FALSE}
# Set eval=TRUE to hide all results and figures.
# This sets defaults. Can change this manually in individual chunks.
# Must load knitr so opts_chunk is in search path.
library(knitr)
opts_chunk$set(results="hide", fig.show="hide", fig.keep="none")
```

```{r, echo=FALSE, message=FALSE, eval=TRUE}
library(knitr)
opts_chunk$set(message=FALSE)
```

###Set up packages, chart themes etc

```{r Set up packages and environment}

#set up chart theme function and load required packages
chart.theme.size = 14
#theme_set(theme_minimal(chart.theme.size)) #minimal theme as default
source("../r_config/r_env_setup.R") #load packages and cutom ggplot theme function and presets



```

###Reddit dataset
```{r reddit data, message=FALSE, echo=TRUE, warning=FALSE}

#load the reddit dataset
reddit_df <- read.csv("../data/reddit.csv", header = T,
                      stringsAsFactors=TRUE, sep=",",
                      nrow = 1000)

#Number of rows and columns
dim(reddit_df)

#List of variables
names(reddit_df)

#structure of the dataset
str(reddit_df)

#levels of employment status
levels(reddit_df$age.range)

#count summary of employement status
table(reddit_df$age.range)

#barblot for age range
foot_text = "Source: xxx"

p<-
ggplot(data = reddit_df, aes(x = age.range)) +
  geom_bar_custom +
  chart_theme_bar +
  theme(axis.text.x = element_text(angle=90, hjust=1, vjust=0.5))+
  annotate("text", x = Inf, y = -Inf, label = "sumitbajaj.me", hjust=1.1, vjust= -.5, col="gray", 
           cex=3, 
           #size = chart.theme.size*.25,
           alpha = 0.8)
print(p)
ggsave("test.png", width=12, height=9, p)

  #chart_footer 
 
  #theme(axis.text.x = element_text(angle=90, hjust=1, vjust=0.5)) +
  #geom_hline(yintercept=0, size=0.75, color="grey") 
#Notice that under18 bucket is at the end which is non-intuitive
```

