---
title: "Maps"
output:
  html_document:
    fig_height: 7
    fig_width: 9
    dpi: 144
    theme: cerulean
    toc: yes
    
---



```{r global_options, include=FALSE}

#http://kbroman.org/knitr_knutshell/pages/Rmarkdown.html
knitr::opts_chunk$set(fig.width=9, 
                      fig.height=7, 
                      fig.path='Figs/',
                      echo=TRUE, 
                      warning=FALSE, 
                      message=FALSE,
                      include = TRUE, #show figures, FALSE will evaluate code but suppress results
                      #fig.show="hide", #if you want to hide figures
                      results = "show"
                      )

knitr::opts_chunk$set(cache=TRUE)

```



#Setup
Set up packages, chart themes, slack notifications etc
```{r Set up packages and environment, include=FALSE, cache=FALSE}

#load packages
source("../../r_config/r_packages_setupv1.R") 

#load custom functions
source("../../r_config/r_functions_repository.R")

#load custom ggplot2 theme functions
source("../../r_config/r_visualization_setupv1.R")

#set default theme for charts
theme_set(chart_theme_custom_base(fsize = 14, background_grey = 0, vgrid = 1, hgrid = 1)) 

#data table global options
options(DT.options = list(pageLength = 5, language = list(search = 'Search:')))
#datatable(head(iris))

#setup slack bot for notifications
setup_slack(token_path = "../../../api_tokens/api_tokens - list.csv", channel_name = "#code_status")

#post a test message
#slackr("Everything setup!")

```



```{r load packages}

library(rgdal)
library(rgeos)
library(ggplot2)
library(readr)
library(tidyr)
library(dplyr)
library(grid)

```

```{r read data and maps shapes}

us <- readOGR("us_states_hexgrid.geojson", "OGRGeoJSON")

centers <- cbind.data.frame(data.frame(gCentroid(us, byid=TRUE), id=us@data$iso3166_2))

us_map <- fortify(us, region="iso3166_2")

intensity <- c(D0="Abnormally Dry", D1="Moderate Drought", D2="Severe Drought",
               D3="Extreme Drought", D4="Exceptional Drought")

today <- format(Sys.Date(), "%Y%m%d")

read_csv(sprintf("http://droughtmonitor.unl.edu/USDMStatistics.ashx/?mode=table&aoi=state&date=%s", today)) %>%
  gather(drought_level, value, D0, D1, D2, D3, D4) %>%
  mutate(intensity=factor(intensity[drought_level],
                          levels=as.character(intensity), ordered=TRUE)) -> drought

```


```{r plot data}

gg <- ggplot()
gg <- gg + geom_map(data=us_map, map=us_map,
                    aes(x=long, y=lat, map_id=id),
                    color="white", size=0.5)
gg <- gg + geom_map(data=drought, map=us_map,
                    aes(fill=value, map_id=State))
gg <- gg + geom_map(data=drought, map=us_map,
                    aes(map_id=State),
                    fill="#ffffff", alpha=0, color="white",
                    show_guide=FALSE)
gg <- gg + geom_text(data=centers, aes(label=id, x=x, y=y), color="white", size=4)
gg <- gg + scale_fill_distiller(name="State\nDrought\nCoverage", palette="RdPu", na.value="#7f7f7f",
                                labels=sprintf("%d%%", c(0, 25, 50, 75, 100)))
gg <- gg + coord_map()
gg <- gg + facet_wrap(~intensity, ncol=2)
gg <- gg + labs(x=NULL, y=NULL, title=sprintf("U.S. Drought Conditions as of %s\n", Sys.Date()))
gg <- gg + theme_bw()
gg <- gg + theme(plot.title=element_text(face="bold", hjust=0, size=24))
gg <- gg + theme(panel.border=element_blank())
gg <- gg + theme(panel.margin=unit(3, "lines"))
gg <- gg + theme(panel.grid=element_blank())
gg <- gg + theme(axis.ticks=element_blank())
gg <- gg + theme(axis.text=element_blank())
gg <- gg + theme(strip.background=element_blank())
gg <- gg + theme(strip.text=element_text(face="bold", hjust=0, size=14))
gg <- gg + theme(legend.position=c(0.75, 0.15))
gg <- gg + theme(legend.direction="horizontal")
gg <- gg + theme(legend.title.align=1)

png(sprintf("%s.png", today), width=800, height=800)
print(gg)
dev.off()


```


#Test area
```{r scrap}

d1 <- ymd_hms("2014-06-01 13:35:52")
d1
d2 <- ymd_hms("2014-06-03 13:35:52")
d2
d1 - d2

ratio <- .51
sprintf("%1.0f%%", 100*ratio)

col_pal = brewer.pal(3, "Set2")

#display.brewer.all() #RdYIGn
# View 5 colors for the Set2 palette
display.brewer.pal(7,"RdYlGn")
col_pal = brewer.pal(7, "RdYlGn")
col_pal[1]

display.brewer.pal(9,"Blues")
blues = brewer.pal(9, "Blues")
col_pal[1]

```

